# -*- coding: utf-8 -*-
"""PruebasPython_Cartera_Recomendada

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LABECUYen_zaWNVGoMNF9lCLmDoV0QyD
"""

!pip install yfinance

import yfinance as yf

ticker_obj = yf.Ticker("MELI")
ticker_obj.get_info()

dataframe = yf.download("MELI")
dataframe

ticker_obj.get_info()

"""'52WeekChange': -0.4231521

'country': 'Argentina',

'beta': 1.53257,

'recommendationKey': 'buy'

'currentPrice': 1156.5,

 'fiftyTwoWeekHigh': 2006.71,

 'fiftyTwoWeekLow': 957.6,

 'logo_url': 'https://logo.clearbit.com/mercadolibre.com',

 'longBusinessSummary': 'MercadoLibre, ...',

 'longName': 'MercadoLibre, Inc.',

'marketCap': 58355834880, 58 BILLONES

'symbol': 'MELI',

"""

df = yf.download("MELI")
df = df.loc["2022-02-01":"2022-02-15", ["Open","Close"]]
df["Rendimiento"] = df.Close.pct_change() *100
df = df.sort_index(ascending=False)
df

import pandas as pd

df = yf.download("MELI", auto_adjust=True)

grouped = pd.DataFrame()
grouped["Min"] = df.Close.groupby(df.index.year).min()
grouped["Max"] = df.Close.groupby(df.index.year).max()
grouped["Precio Ene"] = df.Close.groupby(df.index.year).first()
grouped["Precio Dic"] = df.Close.groupby(df.index.year).last()

#grouped["variacion__nominal"] = grouped ["Precio Ene"].diff()
grouped["Variacion_anual"] = (grouped["Precio Dic"] / grouped ["Precio Ene"] -1) * 100
grouped.round(2)

df = yf.download("MELI", auto_adjust=True, rounding=True)
df ["maximo_historico"] = df.High.cummax()
df ["minimo_historico"] = df.Low.cummin()
df

"""Web scraping Sp"""

#Ejemplo de web scraping
import pandas as pd
sp500 = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
sp500 = sp500[0]

sp500_tickers = list(sp500.Symbol)
len(sp500_tickers)

"""Medias moviles"""

for n in [10, 20, 100]:
  df[f"sma{n}"] = df.Close.rolling(n).mean()

df = yf.download("MELI", auto_adjust=True)

for x in [10,20,100]:
  df[f"sma{x}"] = df.Close.rolling(x). mean()


df = df["2020-01":].copy()
df["Price"] = df.Close
df.Price.plot(color="black", ls="--", legend=True)
df.sma10.plot(color="blue",legend=True) 
df.sma20.plot(color="orange",legend=True)
df.sma100.plot(color="red", title="Cruce 10,20 y 100", figsize= (16,10), grid= False, legend=True)