# -*- coding: utf-8 -*-
"""Vanetta_Agustin_Desafío entregable 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EIUWhJCxGMR2QW1zpnLevxwi0VP5DOuK
"""

type("Hola Mundo")

type([1, 10, 100])

type(-25)

type((8, 100, -12))

type(1.167)

type(["Hola", "Mundo"])

type("")

type((1, -5, "Hola!"))

"""Punto 2"""

a = 10
b = -5
c = "Hola"
d = [1,2,3]
e = (4,5,6)

print(a * 5)  
print(a - b)    
print(c + "Mundo")   
print(c * 2)        
print(c[-1])        
print(c[1:])    
print(d + d)       
print(e[1])
print(e+(7,8,9))

"""3."""

numero_1 = 9
numero_2 = 3
numero_3 = 6
media = str( (numero_1 + numero_2 + numero_3) / 3)
print("La nota media es " + media)

"""4."""

numero_1 = 10
numero_2 = 10
numero_3 = 2

parte_nota_1 = numero_1*0.15
parte_nota_2 = numero_2*0.35
parte_nota_3 = numero_3*0.50

nota_final = (parte_nota_1  + parte_nota_2 + parte_nota_3)

round(nota_final, 2)

"""5"""

matriz = [ 
    [1, 5, 1],
    [2, 1, 2],
    [3, 0, 1],
    [1, 4, 4]
]

suma_list_1 = sum(matriz[0])
suma_list_2 = sum(matriz[1])
suma_list_3 = sum(matriz[2])
suma_list_4 = sum(matriz[3])

matriz[0].append(suma_list_1)
matriz[1].append(suma_list_2)
matriz[2].append(suma_list_3)
matriz[3].append(suma_list_4)

print(matriz)

for i in [0 , 1, 2, 3]:
  matriz[i].append(sum(matriz[i]))

print(matriz)