# -*- coding: utf-8 -*-
"""FuncionesVanettaAgustin

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zXiyoH6DuwimWnyLFtGOSjEKdACUlwgD
"""

## 1) Realiza una función llamada area_rectangulo() 

def area_rectangulo(base, altura):
    return base * altura

area_rectangulo(15, 10)

#2) Realiza una función llamada area_circulo()

import math
###print(math.pi)

def area_circulo(radio):
    return math.pi * radio**2

area_circulo(5)

#3) Realiza una función llamada relacion() 

def relacion(num1, num2):
    if num1 > num2:
        return 1
    elif num1 < num2:
        return -1
    return 0

print(relacion(5, 10), relacion(10, 5), relacion(5, 5))

# 4) Realiza una función llamada intermedio()

def intermedio(num1, num2):
    return (num1 + num2) / 2

intermedio(-12, 24)

# 5) Realizá una función llamada recortar() 

def recortar(num, lim_inf, lim_sup):
    return max(min(num, lim_sup), lim_inf)

recortar(-2, 0, 10)

# 6) Realiza una función separar()
##pares, impares = separar([6,5,2,1,7])
##print(pares)   # valdría [2, 6]
##print(impares)  # valdría [1, 5, 7]

listaDeNumeros = [6, 5, 2, 1, 7]


def separar(*lista):
    lista = sorted(lista)
    pares = []
    impares = []
    for num in lista:
        if num % 2 == 0:
            pares.append(num)
        else:
            impares.append(num)
        
    return pares, impares

pares, impares = separar(*listaDeNumeros)
print(pares)  
print(impares)