# -*- coding: utf-8 -*-
"""IdeaVanettaAgustin

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yD0_zNIEWvjCsyfcckqVehF2pOzX3jDf

Punto 1
"""

numero_1 = int(input("Ingrese un numero\n"))
numero_2 = int(input("Ingrese otro numero\n"))


while type(numero_1) and type(numero_2) == int:
  seleccion_del_usuario = int(input("Seleccione una opcion\n 1.Sumar \n 2.Restar 1ero con el 2do \n 3.Multiplicar \n 4.Opcion Magica \n"))
 
  if (seleccion_del_usuario > 4 or seleccion_del_usuario < 1):
    print("La opcion ingresada no es valida")
  elif (seleccion_del_usuario == 1):
    print(numero_1 + numero_2)

  elif (seleccion_del_usuario == 2):
    print(numero_1 - numero_2)

  elif (seleccion_del_usuario == 3):
    print(numero_1 * numero_2)

  else:
    print("El programa finalizo")
    break

N = int(input().strip())

if (N%2 != 0):
  print("Weird")
elif((N%2 == 0) and N<5 and N>2):
    print("Not Weird")
elif(N % 2 == 0 and N > 20):
    print("Not Weird")
elif(N % 2 == 0 and N<=20 and N>6):
  print("Weird")
else:
  print("corre")

"""Punto 2"""

while (True):
  numero= int(input("Ingrese un numero impar \n"))
  if ((numero % 2) == 0):
    print("El numero no es impar, intente nuevamente")
  else:
    print("El numero es impar")
    break

"""Punto 3"""

range(0, 101, 2)

sum(range(1,101,2))

"""Punto 4"""

lista = []

while (True):
  numero = int(input("Ingresa un numero para añadirlo a la lista \nIngrese 00 para cancelar\n"))
  
  if (numero == 00):
    break

  else:
    lista.append(numero)

  suma = sum(lista)
  cantidad  = len(lista)

  media = suma/cantidad
  print(f"La media aritmetica es {media}")

"""Punto 5"""

lista = [1, 3, 6, 9]

while (True):

  eleccion = int(input("Ingrese un numero del 0 al 9 \n"))
  if (eleccion >= 0 and eleccion <10):
    if (eleccion in lista):
      print("El numero ingresado se encuentra en la lista")
      break
    else:
      print("El numero ingresado NO encuentra en la lista")
  else:
    print("El numero ingresado es incorrecto")

"""Punto 6"""

listaA = list(range(11)) #Todos los números del 0 al 10 [0, 1, 2, ..., 10]
listaB = list(range(-10, 1))#Todos los números del -10 al 0 [-10, -9, -8, ..., 0]
listaC = list(range(2, 20, 2))#Todos los números pares del 0 al 20 [0, 2, 4, ..., 20]
listaD = list(range(-19, 1, 2))#Todos los números impares entre -20 y 0 [-19, -17, -15, ..., -1]
listaE = list(range(5, 50, 5)) #Todos los números múltiples de 5 del 0 al 50 [0, 5, 10, ..., 50]

print(listaA)

"""Punto 7"""

lista_1 = ['h','o','l','a',' ','m','u','n','d','o']
lista_2 = ["h",'o','l','a','o', 'l','u','n','a']
lista_3 = []

lista_b = []
lista_b.append(lista_1)
lista_b.append(lista_2)

for i in lista_1:
  if (lista_1.count(i) >1):
    lista_3.append(i)
    lista_1.remove(i)
for i in lista_2:
  if (lista_2.count(i) >1):
    lista_3.append(i)
    lista_2.remove(i)
for i in lista_3:
  if (lista_3.count(i) >1):
    lista_3.remove(i) 

print(lista_1)
print(lista_2)
print(lista_3)
print(lista_b)

lista_1 = ['h','o','l','a',' ','m','u','n','d','o']
lista_2 = ["h",'o','l','a',' ', 'l','u','n','a']
lista_3 = []

lista_b = lista_1 + lista_2

for i in lista_b:
  if (lista_b.count(i)>1):
    lista_3.append(i)
for i in lista_3:
  if (lista_3.count(i)>1):
    lista_3.remove(i) 


print(lista_1)
print(lista_2)
print(lista_3)
print(lista_b)