# -*- coding: utf-8 -*-
"""FuncionAñoBisiestoVanettaAgustin

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OEdUj0PPVkPnTlYrc_E21IEiZC074Sm_
"""

def esBisiesto(): 
 
  while (True):
    año = input('Ingresa un año: ')
    if(año.isnumeric()):
      año = int(año)
      if año % 4 == 0:
          if año % 100 == 0:
              if año % 400 == 0:
                  print(f'El año {año} es bisiesto')
                  break
              else:
                  print(f'El año {año} no es bisiesto')
                  break
          else:
              print(f'El año {año} es bisiesto')
              break
      else:
          print(f'El año {año} no es bisiesto')
          break
    else:
        print("No ingresaste un numero, intente nuevamente")

esBisiesto()