# -*- coding: utf-8 -*-
"""MiPrimerProgramaEnPythonVanettaAgustin

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ya0l7C9p7CXUPGZNI5Fej5uvlL3dufT9
"""

nota_1 = float(input("Ingrese la nota del primer examen "))
nota_2 = float(input("Ingrese la nota del segundo examen "))
nota_3 = float(input("Ingrese la nota del tercer examen "))

porcentaje_nota_1 = nota_1*0.25
porcentaje_nota_2 = nota_2*0.30
porcentaje_nota_3 = nota_3*0.45

nota_final = (porcentaje_nota_1  + porcentaje_nota_2 + porcentaje_nota_3)

round(nota_final, 2)