# -*- coding: utf-8 -*-
"""Modulo 1 : Conceptos Basicos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oWYrElhBcabRc_8mOhGBoP6937PCuyeF
"""

print("Hola Mundo!")

# esto es un comentario 
saludo = "Hola!"

print (saludo)
saludo

# Operadores logicos or and not

"Hola mundo".find("mundo") # Busca un determinado string y devuelve la posicion donde se encuentra

"123".isdigit()

frase = [ "Hola", "como", "estas", "?" ]
" ".join(frase)

" ".join([ "Hola", "como", "estas", "?" ])

"Hola mundito".replace("mundito", "mundo")

nombre = "Pupino"
mensaje = f"{nombre} les saluda"

print (mensaje)

lista = list(range(10))
lista