# Generated by Django 4.0.4 on 2022-04-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreYApellido', models.CharField(max_length=30)),
                ('dni', models.IntegerField()),
                ('fechaDeNacimiento', models.DateField()),
            ],
        ),
    ]
