# -*- coding: utf-8 -*-
"""Manejo de Archivos y Datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RbryIlZUg_0iv-sGYCTbsVZ9nymxPnxf
"""

#get obtenemos el valor de la clave correspondiente
colores = {1:"yellow", 2:"blue", 3:"green"}
colores.get(2, "NO HAY.")

#keys nos permite conocer las claves del diccionario
colores.keys()

#values nos permite conocer los valores del diccionario
colores.values()

colores = { "amarillo":"yellow", "azul":"blue", "verde":"green" }
colores.items()


for clave, valor in colores.items():
  print(clave, valor)

"""##Archivos"""

from google.colab import drive
drive.mount('/drive/')

ruta = "/drive/MyDrive/Comision 27615"

"""Con write ("w") creamos.
Vamos de Python a .txt

"""

#abrimos (si el archivo no existe lo creamos) un archivo 
f = open(ruta + "/prueba.txt","w") #el w es el permiso de escritura (write)

f.write("Hola, este es mi primer archivo")  #con el write escribimos dentro del archivo txt

f.close() #siempre es bueno cerrar el archivo al final

#Ejemplo diccionarios+files
nombre = "Nicolas"
apellido = "Perez"
dni = 111111

d = {"NOMBRE":nombre, "APELLIDO":apellido, "DNI":dni}

f = open(ruta + "/otro.txt", "w")

f.write(d["NOMBRE"] +"," +d["APELLIDO"] +"," +str(d["DNI"] ))

f.close()

"""Con read ("r") leemos el archivo. De .txt a Python

Si al read() o al readline() le ponen un número dentro de los paréntesis entonces van a leer dicha cantidad de caracteres en lugar de leer todo el archivo (read) o toda la linea (readline).
"""

f = open(ruta + "/paraLeer.txt", "r") #abro el archivo pero en modo lectura

content = f.read()  #copiando el archivo y guardando dentro de la variable content
print(content)  #imprimir los datos del archivo (que se guardaron en content)

f.close() #la buena práctica de cerrar el archivo

f = open(ruta + "/paraLeer.txt", "r")

print(f.readline()) #uso la funcion readline() para leer SOLAMENTE UNA línea del archivo.

f.close()

f = open(ruta + "/paraLeer.txt", "r") #abro el archivo

for line in f.readlines():  #por cada linea que hay en el archivo
    print(line) #imprimo cada línea


f.close()

f = open(ruta + "/paraLeer.txt", "r")

f.seek(32)  #el seek es una acción que te muestra el archivo desde cierto índice.

print(f.read())


f.close()

import json  #Importar las funciones de json 
#clase 15 entenderemos mejor el IMPORT

data = {}

data['clients'] = []

data['clients'].append({
    'first_name': 'Sigrid',
    'last_name': 'Mannock',
    'age': 27,
    'amount': 7.17})

data['clients'].append({
    'first_name': 'Joe',
    'last_name': 'Hinners',
    'age': 31,
    'amount': [1.90, 5.50]})

data['clients'].append({
    'first_name': 'Theodoric',
    'last_name': 'Rivers',
    'age': 36,
    'amount': 1.11})


with open(ruta + "/primerJson.json", 'w') as file:
    json.dump(data, file, indent=4) #dump el equivalente a write

with open(ruta + "/primerJson.json","r") as file:

    dataLectura = json.load(file)

    for client in dataLectura['clients']:
        print('First name:', client['first_name'])
        print('Last name:', client['last_name'])
        print('Age:', client['age'])
        print('Amount:', client['amount'])
        print('')

#Para generar una variable con los datos de nuestro archivos, vamos a empezar a trabajar con nuestra libreria "magica" para trabajar con datos, 
#libreria llamada Pandas, para poder usarla debemos hacer lo siguiente

import pandas as pd  #En castellano, importamos pandas y lo llamamos pd  (pd puede ser cualquier palabra que recuerden)

import numpy as np #Esto lo usaremos bastante mas adelante del apunte, por ahora se lo puede ignorar

#En mi caso voy a abrir los datos de calidad de aire

variableCalidad = pd.read_csv(ruta+ "/calidad-aire.csv")

#Acá se vé que era necesario tener pandas, ya que usamos la función read_csv de pandas.
#LISTO... Ya tenemos todos nuestros datos leidos y guardados en una variable... Ya son "facilmente" manipulables.

variableCalidad

variableCalidad.head(3) #para ver las 3 primeras filas

"""##Ejercicio de repetitivas

###Crear un programa que les pida una altura de un árbol y ustede dibujen el árbol de acuerdo a lo que les indicó el usuario.

Ejemplo:

Ingrese el tamaño del árbol: 5

    #
   ###
  #####
 #######
#########
    #

Ingrese el tamaño del árbol: 3


  #
 ###
#####
  #

Como gusten pueden usar while o for.
"""

