# -*- coding: utf-8 -*-
"""vivoClase12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bVDc-qE5O-OTKGXhJ0RJv-VcOlKC1__u
"""

#Ejemplo de repaso --- Trabajar con los datos de un "vehiculo"

#varaible = input().....
marca = "FIAT"
modelo = "Palio"
color = "Gris"
patente = "AA123LL"
anio = 2001

#Función para mostrar los datos de un vehiculo

def mostrarVehiculo(mar,mod,col,pat,an):

  print("--------------------------")
  print(f"MARCA: {mar}")
  print(f"MODELO: {mod}")
  print(f"COLOR: {col}")
  print(f"AÑO: {an}")
  print(f"PATENTE: {pat}")
  print("--------------------------")

mostrarVehiculo(marca,modelo,color,patente,anio)

mostrarVehiculo("Renault", "Clio", "Rojo", "b112JJ",2010)

mostrarVehiculo(col = "Verde", mar ="FORD", an = 1980,pat = "DDDDD",mod ="Taunus")

#En resumen 

#auto1.mostrarVehiculo()

"""#Para probar en:  https://www.planttext.com/

@startuml

title Primer Diagrama Coder


class Profesor{
 nombre: String
+apellido: String
-doc: float
#edad: int

-mostrarTarea(List nadie): void
+enseñar(): void
+desaprobarATodos(): Boolean
+aprobar(Estudiante nadia): int


}


class Estudiante{

-codEstudiante
-nombre
-promedio

+cursar()
+entragarTarea()
+rendir()

}

class Curso{

-nombre
-comision
-horario

+generarZoom()
+matricularEstudiante()

}

Profesor "1" *-- "..*"  Curso

Curso "0..*" o-- "1..*" Estudiante

Profesor "1..6" --> "1..*" Estudiante: Ama ♥ 


@enduml
"""

